FROM node:18-alpine AS build
WORKDIR /app

# Получить переменную при сборке
ARG REACT_APP_API_URL
ENV REACT_APP_API_URL=$REACT_APP_API_URL

COPY package*.json ./
RUN npm install --include=dev

COPY . .
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html

# Копировать nginx конфигурацию для SPA
COPY nginx.conf /etc/nginx/conf.d/default.conf
