version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: ushe_luche_postgres_prod
    environment:
      POSTGRES_DB: ushe_luche_prod
      POSTGRES_USER: ushe_luche_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-your_secure_password_here}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups
    restart: unless-stopped
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ushe_luche_user -d ushe_luche_prod"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ushe_luche_backend_prod
    environment:
      - DATABASE_URL=postgresql://ushe_luche_user:${POSTGRES_PASSWORD:-your_secure_password_here}@postgres:5432/ushe_luche_prod
      - SECRET_KEY=${SECRET_KEY:-your_super_secret_key_here_change_in_production}
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - CORS_ORIGINS=${CORS_ORIGINS:-https://snowbetter.ru,https://www.snowbetter.ru}
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
    volumes:
      - ./uploads:/app/uploads
      - ./backend/app:/app/app
      - ./backend/requirements.txt:/app/requirements.txt
      - ./logs:/app/logs
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: ushe_luche_frontend_prod
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL:-https://snowbetter.ru}
      - REACT_APP_ENVIRONMENT=production
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - app_network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: ushe_luche_nginx_prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./logs/nginx:/var/log/nginx
      - ./uploads:/var/www/uploads:ro
    restart: unless-stopped
    depends_on:
      - frontend
      - backend
    networks:
      - app_network

  # Let's Encrypt Certbot
  certbot:
    image: certbot/certbot
    container_name: ushe_luche_certbot_prod
    volumes:
      - ./nginx/ssl:/etc/letsencrypt
      - ./nginx/webroot:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email ${CERTBOT_EMAIL:-admin@snowbetter.ru} --agree-tos --no-eff-email -d ${DOMAIN:-snowbetter.ru} -d www.${DOMAIN:-snowbetter.ru}
    depends_on:
      - nginx
    networks:
      - app_network

  # Redis for caching (optional, for future scaling)
  redis:
    image: redis:7-alpine
    container_name: ushe_luche_redis_prod
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-your_redis_password_here}
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  app_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
