FROM python:3.11-slim

WORKDIR /app

# Устанавливаем зависимости раньше, чтобы слои кэшировались
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем код и вспомогательные файлы
COPY . .

# Если нужен tricks.json внутри контейнера:
COPY tricks.json ./tricks.json

# Запуск без --reload для production
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
